kernel:
  image: linuxkit/kernel:4.9.40
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:906e174b3f2e07f97d6fd693a2e8518e98dafa58
  - linuxkit/runc:90e45f13e1d0a0983f36ef854621e3eac91cf541
  - linuxkit/containerd:7c986fb7df33bea73b5c8097b46989e46f49d875
  - linuxkit/ca-certificates:e44b0a66df5a102c0e220f0066b0d904710dcb10
onboot:
  - name: sysctl
    image: linuxkit/sysctl:154913b72c6f1f33eb408609fca9963628e8c051
  - name: sysfs
    image: linuxkit/sysfs:3ae01a25583ee37a5ff8b09a0e569cb4bd8cf2e9
  - name: dhcpcd
    image: linuxkit/dhcpcd:f3f5413abb78fae9020e35bd4788fa93df4530b7
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-I", "master", "-1"]
  - name: metadata
    image: linuxkit/metadata:cec86f3e1c260c9eafefa80c262fceb40c182ddf
  - name: format
    image: linuxkit/format:158d992b7bf7ab984100c697d7e72161ea7d7382
  - name: mounts
    image: linuxkit/mount:4fe245efb01384e42622c36302e13e386bbaeb08
    command: ["/usr/bin/mountie", "/var/lib/"]
  - name: var
    image: library/alpine:3.6
    command: ["mkdir", "/var/lib/kubeadm"]
    binds:
      - /var/lib:/var/lib
services:
  - name: getty
    image: linuxkit/getty:2c841cdc34396e3fa8f25b62d112808f63f16df6
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:558e86a36242bb74353bc9287b715ddb8567357e
  - name: ntpd
    image: linuxkit/openntpd:0d7befc79842849d0b88d6c3b64200e340d7cf67
  - name: sshd
    image: linuxkit/sshd:505a985d7bd7a90f15eca9cb4dc6ec92789d51a0
  - name: docker
    image: docker:17.06.0-ce-dind
    capabilities:
     - all
    pid: host
    mounts:
     - type: cgroup
       options: ["rw","nosuid","noexec","nodev","relatime"]
    binds:
     - /dev:/dev
     - /etc/resolv.conf:/etc/resolv.conf
     - /lib/modules:/lib/modules
     - /run:/run
     - /var:/var:rshared,rbind
     - /var/lib/kubeadm:/etc/kubernetes
     - /etc/cni:/etc/cni:rshared,rbind
     - /opt/cni:/opt/cni:rshared,rbind
    rootfsPropagation: shared
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
  - name: kubernetes-image-cache-common
    image: linuxkitprojects/kubernetes-image-cache-common:ba16b1f8cfe4f415a5946d521e59f67eaeecd9ce
  - name: kubernetes-image-cache-control-plane
    image: linuxkitprojects/kubernetes-image-cache-control-plane:ba16b1f8cfe4f415a5946d521e59f67eaeecd9ce
  - name: kubelet
    image: linuxkitprojects/kubernetes:bbf14d70199babeea1f71f5b0bd70c1c1c9b5cd2
files:
  - path: root/.ssh/authorized_keys
    source: ~/.ssh/id_rsa.pub
    mode: "0600"
    optional: true
  - path: etc/hostname
    contents: "master"
  - {path: etc/cni, directory: true}
  - {path: opt/cni, directory: true}
